# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94f39667776029d8870b71f617322e0cdff37ff2fe6fac81b086f1d48dc381be143e4389113d618b0c288f164552425fc68a84c5d32b4d65d404b2d7626823e0

test:
  secret_key_base: 4e1bc87abbd1e8b4bdfaa5dec85714499cca668e4d4ddc79ec6f638d7ba135568fe88d1ed25e325c9af8ae388e9ba23b5f6c2f16dc14ba6a9405861c78a0d8d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
